### PR TITLE
Fix clearRelationships on hasMany relationships when record is deleted

### PR DESCRIPTION
**Pull request by Dylnuge**
Backport from now until ember-data beta.7 (partial backport of https://github.com/emberjs/data/commit/f6666e5a858fa4d1860471beaaeb42b5dac56af8). Required for hasMany relationships to properly clear out when a model is deleted.

One of two bugs @sicasli and I found today. The other (that inverse relationships do not properly clear out) is resolved in ember-data beta.12. Enough stuff happens between then and where we are now and it's not pressing enough that I'm voting we don't try to backport it and just get the upgrade train rolling.

When a record with hasMany relationships is deleted, we need to clear out all of
its relations. This requires clearing the array hasMany relations are stored in.
The code to do this references `relationship.name` which is a nonexistent
property, so nothing ever gets cleared. The intent is to reference `name`
directly.

@cyril-sf @sicasli

### CODE REVIEW

**Comment by cyril-sf** [comment]
I think we want `relationship.key` ( just to stay consistent with the rest of the code )

**Comment by Dylnuge** [comment]
I thought that too but the change by Stef moves it to `name`?

**Comment by cyril-sf** [comment]
Sure that's fine.

LGTM

**Comment by Dylnuge** [comment]
I never merged this. @sreenath-addepar do we want this?

**Pull request closed without merging**
